version: "3.9"
services:
  front:
    container_name: talentum_talents
    image: 835003931308.dkr.ecr.us-east-1.amazonaws.com/cidt-talentum-talents-frontend:latest
    ports: 
      - "3000:3000"
    restart: on-failure
