<template>
  <span class="title">
    Add an extra layer of security to protect your account. Reach a higher level of security!
  </span>
  <div class="auth">
    <div class="w-full flex justify-between">
      <div class="google">
        <Icon icon="Google_Authenticator" :size="24"></Icon> Google Authenticator
      </div>
      <div v-if="status" class="status">
        <Icon icon="Tik" class="icon" :size="16"></Icon>Activated
      </div>
    </div>
    <div v-if="!status" class="manual">
      <div class="first">
        <span>1. Install </span>
        <a
          href="https://support.google.com/accounts/topic/2954345?hl=en&ref_topic=7667090&sjid=12955798721851683229-EU"
          target="_blank"
          class="link"
          >Google Authenticator</a
        >
        <span> application</span>
        <span> on your device.</span>
      </div>
      <span> 2. Open the app and scan the QR code: </span>
      <div class="qr-block">
        <img :src="QR.qr_code_url" alt="" />
        <div class="desc">
          <div class="subtitle">Or enter the code manually</div>
          <div class="code copy" @click="copyToClipboard">
            <span class="text">{{ QR.code }} </span>
            <Icon icon="Copy" :size="16" />
          </div>
        </div>
      </div>
      <span> 3. Enter the 6-digit code created in the app. </span>
      <div class="input-container">
        <input
          class="auth-input"
          v-for="(input, index) in 6"
          :key="index"
          :class="{ 'error-border': error }"
          v-model="code[index]"
          @input="handleInput"
          @keypress="isNumber"
          @keydown.delete="handleDelete"
          @paste="onPaste"
          maxlength="1"
          type="text"
          inputmode="numeric"
          pattern="[0-9]*"
          ref="inputRefs"
        />
        <div class="activate" @click="activate">Activate</div>
      </div>
    </div>
    <div v-else class="notification">
      <div class="title">
        Your security codes are generated by Google Authenticator app on your smartphone.
      </div>
      <div class="deactivate" @click="showTooltips = !showTooltips">Deactivate</div>
      <div v-if="showTooltips" id="tooltip-confirmation">
        <div class="tooltip-arrow"></div>
        <div class="menu">
          <div class="alert">
            Deactivate 2-Step Authentication?  Your account will lose  a layer of security.
          </div>
          <div class="w-full flex justify-around mt-2">
            <div class="link" @click="showTooltips = !showTooltips">Cancel</div>
            <div class="revoke" @click="diactivate">Confirm</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, inject } from 'vue';
import AxiosService from '~/service/axiosService';
import { useUserStore } from '~/store/user';

export default {
  name: 'TwoStepAuth',
  setup() {
    const digits = ref([0, 1, 2, 3, 4, 5]);
    const code = ref([]);
    const dataFromPaste = ref([]);
    const keysAllowed = ref(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']);
    const showTooltips = ref(false);

    const isNumber = (event) => {
      event.currentTarget.value = '';
      const keyPressed = event.key;
      if (!keysAllowed.value.includes(keyPressed)) {
        event.preventDefault();
      }
    };
    const error = ref(false);
    const nuxtApp = useNuxtApp();

    const copyToClipboard = async () => {
      await navigator.clipboard.writeText(QR.value.code);
      nuxtApp.$alert.show('Copied', {
        type: 'success',
        timeout: 5000,
      });
    };
    const handleInput = (event) => {
      const inputType = event.inputType;
      let currentActiveElement = event.target;
      if (inputType === 'insertText') currentActiveElement.nextElementSibling?.focus();
      if (inputType === 'insertFromPaste' && dataFromPaste.value) {
        for (const num of dataFromPaste.value) {
          let id = parseInt(currentActiveElement.id.split('_')[1]);
          currentActiveElement.value = num;
          code.value[id] = num;
          if (currentActiveElement.nextElementSibling) {
            currentActiveElement = currentActiveElement.nextElementSibling;
            currentActiveElement.nextElementSibling?.focus();
          }
        }
      }
    };

    const handleDelete = (event) => {
      let value = event.target.value;
      let currentActiveElement = event.target;
      if (!value) currentActiveElement.previousElementSibling?.focus();
    };

    const onPaste = (event) => {
      dataFromPaste.value = event.clipboardData?.getData('text').trim().split('');
      if (dataFromPaste.value) {
        for (const num of dataFromPaste.value) {
          if (!keysAllowed.value.includes(num)) event.preventDefault();
        }
      }
    };

    const activate = () => {
      error.value = false;
      if (code.value.length < 6) {
        error.value = true;
        return;
      }
      AxiosService.post(useRuntimeConfig().public.apiBaseV2 + `profile/2fa `, {
        code: code.value.join(''),
      })
        .then(() => {
          nuxtApp.$alert.show('2-Step Authentication was successfully activated.', {
            type: 'success',
            timeout: 5000,
          });
          useUserStore().userInfo();
        })
        .catch(() => {
          nuxtApp.$alert.show(
            "Sorry, we're currently unable  to process your request. Please try again later.",
            {
              type: 'error',
              timeout: 5000,
            },
          );
          error.value = true;
        });
    };

    const diactivate = () => {
      showTooltips.value = !showTooltips.value;
      AxiosService.delete(useRuntimeConfig().public.apiBaseV2 + `profile/2fa `, {})
        .then(() => {
          useUserStore().userProfile();
          nuxtApp.$alert.show('2-Step Authentication was successfully deactivated.', {
            type: 'success',
            timeout: 5000,
          });
        })
        .catch(() => {
          nuxtApp.$alert.show(
            "Sorry, we're currently unable  to process your request. Please try again later.",
            {
              type: 'error',
              timeout: 5000,
            },
          );
        });
    };
    const QR = computed(() => useUserStore().getQR);
    const status = computed(() => useUserStore().getUser.google2fa_enabled);

    return {
      digits,
      code,
      dataFromPaste,
      keysAllowed,
      status,
      showTooltips,
      QR,
      isNumber,
      handleInput,
      handleDelete,
      onPaste,
      activate,
      diactivate,
      copyToClipboard,
      error,
    };
  },
};
</script>

<style scoped lang="scss">
.copy {
  &:hover {
    cursor: pointer;
  }
}
#tooltip-confirmation {
  position: absolute;
  width: 200px;
  height: fit-content;
  margin-top: 105px;
  background: $white;
  padding: 13px 16px;
  box-shadow: 0px 4px 16px rgba(56, 64, 91, 0.24);
  border-radius: 8px;
  font-family: 'Basis Grotesque Pro';
  font-style: normal;
  font-weight: 500;
  font-size: 12px;
  line-height: 16px;
  letter-spacing: 0.014em;
  font-feature-settings: 'tnum' on, 'lnum' on, 'zero' on;
  .tooltip-arrow {
    position: absolute;
    top: -6px;
    left: 15%;
    transform: translateX(-50%);
    width: 0;
    height: 0;
    border-left: 6px solid transparent;
    border-right: 6px solid transparent;
    border-bottom: 6px solid $white;
  }
  .menu {
    display: flex;
    justify-content: space-between;
    flex-direction: column;
    gap: 8px;
    .link {
      font-family: 'Basis Grotesque Pro';
      font-style: normal;
      font-weight: 500;
      font-size: 14px;
      line-height: 20px;
      font-feature-settings: 'zero' on;
      color: $default;
      &:hover {
        cursor: pointer;
      }
    }
    .alert {
      font-family: 'Basis Grotesque Pro';
      font-style: normal;
      font-weight: 400;
      font-size: 12px;
      line-height: 16px;
      text-align: center;
      letter-spacing: 0.014em;
      hanging-punctuation: first last;
      list-style-position: outside;
      font-feature-settings: 'tnum' on, 'lnum' on, 'zero' on;
      color: #38405b;
    }
    .revoke {
      font-family: 'Basis Grotesque Pro';
      font-style: normal;
      font-weight: 500;
      font-size: 14px;
      line-height: 20px;
      font-feature-settings: 'zero' on;
      color: $red;
      &:hover {
        cursor: pointer;
      }
    }
    hr {
      color: $default-border;
    }
  }
}
.title {
  font-family: 'Basis Grotesque Pro';
  font-style: normal;
  font-weight: 400;
  font-size: 12px;
  line-height: 16px;
  display: flex;
  align-items: center;
  text-align: center;
  letter-spacing: 0.014em;
  hanging-punctuation: first last;
  list-style-position: outside;
  padding: 0;
  font-feature-settings: 'tnum' on, 'lnum' on, 'zero' on;
  color: $section-title;
}
.auth {
  background: $white;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 16px;
  gap: 16px;
  border: 1px solid #eaeafb;
  border-radius: 16px;
  position: relative;
  .icon {
    filter: invert(51%) sepia(59%) saturate(4547%) hue-rotate(356deg) brightness(101%) contrast(98%);
  }
  .status {
    display: flex;
    gap: 4px;
    color: $orange;
    font-family: 'Basis Grotesque Pro';
    font-style: normal;
    font-weight: 400;
    font-size: 12px;
    line-height: 16px;
    text-align: right;
    letter-spacing: 0.014em;
    hanging-punctuation: first last;
    list-style-position: outside;
    padding: 0;
    font-feature-settings: 'tnum' on, 'lnum' on, 'zero' on;
  }
  .google {
    display: flex;
    align-items: center;
    gap: 8px;
    font-family: 'Basis Grotesque Pro';
    font-style: normal;
    font-weight: 500;
    font-size: 14px;
    line-height: 20px;
    text-align: center;
    font-feature-settings: 'zero' on;
    color: $section-title;
  }
  .manual {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    padding: 0px;
    gap: 16px;

    .qr-block {
      display: flex;
      align-items: flex-end;
      gap: 16px;
      img {
        width: 96px;
        height: 96px;
      }
      .desc {
        display: flex;
        flex-direction: column;
        gap: 8px;
        .subtitle {
          font-family: 'Basis Grotesque Pro';
          font-style: normal;
          font-weight: 400;
          font-size: 16px;
          line-height: 24px;
          display: flex;
          align-items: center;
          font-feature-settings: 'tnum' on, 'lnum' on, 'zero' on;
          color: $secondary;
        }
        .code {
          width: fit-content;
          height: 24px;
          padding: 3px 8px;
          background: $white;
          border-radius: 6px;
          display: flex;
          align-items: center;
          gap: 8px;
          border: 1px solid $default-border;
          .text {
            overflow: hidden;
            font-weight: 500;
            font-size: 12px;
            line-height: 16px;
            color: $default;
          }
        }
      }
    }
    .input-container {
      display: flex;
      margin: 0 auto;
    }

    .auth-input {
      width: 32px;
      height: 32px;
      text-align: center;
      background: $white;
      border: 1px solid $default-border;
      border-radius: 8px;
      margin-right: 8px;
      outline: none;
      font-family: 'Basis Grotesque Pro';
      font-style: normal;
      font-weight: 400;
      font-size: 16px;
      line-height: 24px;
      font-feature-settings: 'tnum' on, 'lnum' on, 'zero' on;
      color: $section-title;
    }
    .activate {
      display: flex;
      flex-direction: row;
      justify-content: center;
      align-items: center;
      padding: 4px 16px;
      gap: 8px;
      width: 120px;
      height: 32px;
      background: $orange;
      border-radius: 8px;
      font-family: 'Basis Grotesque Pro';
      font-style: normal;
      font-weight: 500;
      font-size: 14px;
      line-height: 20px;
      font-feature-settings: 'zero' on;
      color: $white;
      &:hover {
        cursor: pointer;
        background: $orange-active;
      }
    }
    span {
      font-family: 'Basis Grotesque Pro';
      font-style: normal;
      font-weight: 400;
      font-size: 16px;
      line-height: 24px;
      display: flex;
      align-items: center;
      font-feature-settings: 'tnum' on, 'lnum' on, 'zero' on;
      color: $secondary;
    }
    .link {
      font-family: 'Basis Grotesque Pro';
      font-style: normal;
      font-weight: 400;
      font-size: 16px;
      line-height: 24px;
      display: flex;
      align-items: center;
      font-feature-settings: 'tnum' on, 'lnum' on, 'zero' on;
      color: $orange;
    }
  }
}
.notification {
  display: flex;
  flex-direction: column;
  gap: 16px;
  .title {
    font-family: 'Basis Grotesque Pro';
    font-style: normal;
    font-weight: 400;
    font-size: 16px;
    line-height: 24px;
    display: flex;
    align-items: center;
    text-align: left;
    font-feature-settings: 'tnum' on, 'lnum' on, 'zero' on;
    color: $secondary;
  }
  .deactivate {
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    padding: 4px 16px;
    gap: 8px;
    width: 101px;
    height: 32px;
    font-family: 'Basis Grotesque Pro';
    font-style: normal;
    font-weight: 500;
    font-size: 14px;
    line-height: 20px;
    font-feature-settings: 'zero' on;
    color: $default;
    background: $default-border;
    border-radius: 8px;
    &:hover {
      cursor: pointer;
    }
  }
}
.error-border {
  border: 1px solid $error-border !important;
}
.first {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  .link {
    text-decoration: none;
    color: $orange;
  }
}
</style>
